cc_library(
    name = "common",
    hdrs = ["common.h"],
    deps = [
        ":macros",
    ],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "macros",
    hdrs = ["macros.h"],
    visibility = ["//visibility:public"],
)
